version: '3.0'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./testwahelp:/testwahelp
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - php
    networks:
      - testwahelp
    ports:
      - "80:80"
  db:
    build:
      context: ./docker/db
    container_name: ${PROJECT_NAME}-db
    ports:
      - "54321:5432"
    networks:
      - testwahelp
  php:
    build:
      context: ./docker/php
    volumes:
      - ./testwahelp:/testwahelp
    container_name:  ${PROJECT_NAME}-php
    depends_on:
      - db
    restart: always
    networks:
      - testwahelp
networks:
  testwahelp:
    name: testwahelp
